apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction-api
  labels:
    app: churn-prediction-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-prediction-api
  template:
    metadata:
      labels:
        app: churn-prediction-api
    spec:
      containers:
      - name: api
        image: churn-prediction:latest
        ports:
        - containerPort: 8000
        env:
        - name: SQL_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: churn-secrets
              key: sql-server-host
        - name: SQL_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: churn-secrets
              key: sql-username
        - name: SQL_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: churn-secrets
              key: sql-password
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: churn-prediction-service
spec:
  selector:
    app: churn-prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
